# Generated by the glinet-cli release workflow — do not edit by hand.
class GlinetCli < Formula
  desc "Command-line interface for GL.iNet routers"
  homepage "https://github.com/antavik/glinet-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/antavik/glinet-cli/releases/download/v0.1.1/glinet-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "1e99f82b5e76f960b2c961ef427217e77e262c29b118df6bce668aa87915a66d"
    end
    on_intel do
      url "https://github.com/antavik/glinet-cli/releases/download/v0.1.1/glinet-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "eb0889c5c482ce4e96b73aea5c27ca5aceee04ef2855766f0adc9e69393ee353"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/antavik/glinet-cli/releases/download/v0.1.1/glinet-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "a092f6b9758fb99ff25b03f91aa1d8e6d2c8b83056c2132a52e872028791f522"
    end
    on_intel do
      url "https://github.com/antavik/glinet-cli/releases/download/v0.1.1/glinet-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "82716ffdf2cdce2f95ec54c3f82d7b52d806a9d654b631fba4224b3b004fe240"
    end
  end

  def install
    bin.install "glinet-cli"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glinet-cli --version")
  end
end
