# Generated by the glinet-cli release workflow — do not edit by hand.
class GlinetCli < Formula
  desc "Command-line interface for GL.iNet routers"
  homepage "https://github.com/antavik/glinet-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/antavik/glinet-cli/releases/download/v0.3.1/glinet-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "d6b6d7f2f2911d923717024099764ba4f01af46a8f999ae8a12597cd1d75c763"
    end
    on_intel do
      url "https://github.com/antavik/glinet-cli/releases/download/v0.3.1/glinet-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "9f552c7de4cdc88f3d6d92059a69ce1a41302a03762d2d3a3098b02659c70a45"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/antavik/glinet-cli/releases/download/v0.3.1/glinet-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "666d21eb649804804dec3f09841630cfcd22c23549728698bc241a0dc9ae8642"
    end
    on_intel do
      url "https://github.com/antavik/glinet-cli/releases/download/v0.3.1/glinet-cli_0.3.1_linux_amd64.tar.gz"
      sha256 "40dac7e5c138656baf7e816202a3977f1f07ab0c88705e5a1991f8dc15ac309e"
    end
  end

  def install
    bin.install "glinet-cli"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glinet-cli --version")
  end
end
